Simpler container building with multi-stage builds
This couples the build process closer to the directory structure, but
removing things like the `build` directory is nice.

diff --git a/containers/Makefile b/containers/Makefile
--- a/containers/Makefile
+++ b/containers/Makefile
@@ -1,58 +1,36 @@
 .DEFAULT_GOAL := help
 
 .PHONY: all
-all:
+all: ## build everything
 	@for NAME in $$(ls); do \
 		if [ -r "$${NAME}/main.go" ]; then \
 			$(MAKE) container NAME="$${NAME}"; \
 		fi;\
 	done
 
-.PHONY: clean
-clean:
-	@for NAME in $$(ls); do \
-		if [ -r "$${NAME}/main.go" ]; then \
-			$(MAKE) clean-container NAME="$${NAME}"; \
-		fi;\
-	done
-
-.PHONY: container
-container: check-env go-build docker-build docker-push
-
-.PHONY: check-env
-check-env:
-	$(if ${NAME},,$(error Must pass NAME of container directory))
-
-.PHONY: go-build
-go-build: check-env
-	cd "${NAME}" && \
-	mkdir -p build && \
-	CGO_ENABLED=0 GOOS=linux go build \
-	  -a -installsuffix cgo \
-	  -o "build/${NAME}" \
-	  .
-
-.PHONY: docker-build
-docker-build: check-env
-	cd "${NAME}" && \
-	cp ../ca-certificates.crt build/ca-certificates.crt && \
-	cp ../Dockerfile build/Dockerfile && \
+.PHONY: container container-env
+container: container-env ## build a container named NAME
 	docker build \
-		-t "${NAME}" \
-		-f build/Dockerfile \
+		-t "46bit/${NAME}" \
+		-f Dockerfile \
 		--build-arg NAME="${NAME}" \
 		.
-
-.PHONY: docker-push
-docker-push: check-env
-	docker tag "${NAME}" "46bit/${NAME}"
 	docker push "46bit/${NAME}"
+container-env:
+	$(if ${NAME},,$(error Must pass NAME of container directory))
+	$(eval export FILE="${NAME}/main.go")
+	@if [ ! -r "${FILE}" ]; then \
+		echo "container '${NAME}' not found in '${FILE}'"; \
+		exit 1; \
+	fi
 
-.PHONY: clean-container
-clean-container: check-env
-	cd "${NAME}" && \
-	rm -rf build && \
-	docker rmi "46bit/${NAME}"
+.PHONY: clean
+clean: ## remove container artifacts
+	@for NAME in $$(ls); do \
+		if [ -r "$${NAME}/main.go" ]; then \
+			docker rmi "46bit/$${NAME}"; \
+		fi;\
+	done
 
 help:
 	@awk -F":.*## " '$$2&&$$1~/^[a-zA-Z_%-]+/{printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
